# Generated by Django 5.2 on 2025-05-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(editable=False, max_length=11, unique=True, verbose_name='Número de seguimiento')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('status', models.CharField(choices=[('preparation', 'En preparación'), ('transit', 'En tránsito'), ('branch', 'En sucursal'), ('delivered', 'Entregado'), ('canceled', 'Cancelado')], default='preparation', verbose_name='Estado')),
                ('sender', models.CharField(max_length=100, verbose_name='Remitente')),
                ('recipient', models.CharField(max_length=100, verbose_name='Destinatario')),
                ('package_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Importe de bultos')),
                ('envelope_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Importe de sobres')),
                ('total_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Importe total')),
            ],
            options={
                'verbose_name': 'envio',
                'verbose_name_plural': 'envios',
            },
        ),
    ]
