# Generated by Django 5.2 on 2025-05-08 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackageCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('mount', models.IntegerField(verbose_name='Monto')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias de paquetes',
            },
        ),
        migrations.CreateModel(
            name='PaymentCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias de pago',
            },
        ),
        migrations.CreateModel(
            name='StatusCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias de estado',
            },
        ),
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(editable=False, max_length=11, unique=True, verbose_name='Número de seguimiento')),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/', verbose_name='Código QR')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('sender', models.CharField(max_length=100, verbose_name='Remitente')),
                ('recipient', models.CharField(max_length=100, verbose_name='Destinatario')),
                ('phone', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('envelope_amount', models.IntegerField(blank=True, null=True, verbose_name='Importe de sobre')),
                ('package_pickups', models.IntegerField(blank=True, null=True, verbose_name='Recogida de paquetes')),
                ('total_amount', models.IntegerField(blank=True, null=True, verbose_name='Importe total')),
                ('package_amount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.packagecategories', verbose_name='Importe de paquete')),
                ('payment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paymentcategories', verbose_name='Tipo de pago')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.statuscategories', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
                'ordering': ['-creation_date'],
            },
        ),
    ]
