# Generated by Django 5.2 on 2025-05-07 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias de pago',
            },
        ),
        migrations.CreateModel(
            name='StatusCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias de estado',
            },
        ),
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(editable=False, max_length=11, unique=True, verbose_name='Número de seguimiento')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('sender', models.CharField(max_length=100, verbose_name='Remitente')),
                ('recipient', models.CharField(max_length=100, verbose_name='Destinatario')),
                ('package_amount', models.IntegerField(blank=True, null=True, verbose_name='Importe de bultos')),
                ('envelope_amount', models.IntegerField(blank=True, null=True, verbose_name='Importe de sobres')),
                ('package_pickups', models.IntegerField(blank=True, null=True, verbose_name='Recogida de paquetes')),
                ('total_amount', models.IntegerField(blank=True, null=True, verbose_name='Importe total')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paymentcategories', verbose_name='Tipo de pago')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.statuscategories', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'envio',
                'verbose_name_plural': 'envios',
            },
        ),
    ]
