# Generated by Django 5.2 on 2025-05-08 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipments',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Envío', 'verbose_name_plural': 'Envíos'},
        ),
        migrations.RemoveField(
            model_name='paymentcategories',
            name='description',
        ),
        migrations.RemoveField(
            model_name='statuscategories',
            name='description',
        ),
        migrations.AddField(
            model_name='shipments',
            name='phone',
            field=models.CharField(default='', max_length=10, verbose_name='Teléfono'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipments',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qrcodes/', verbose_name='Código QR'),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.statuscategories', verbose_name='Estado'),
        ),
    ]
